@startuml

class Elevator
{
    - id: str
    - speed: float
    - minFloor: Integer
    - maxFloor: Integer
    - closeTime: float
    - openTime: float
    - startTime: float
    - stopTime: float
    - calls: list
    + load_from_jfile(self, file_name: str) -> dict
    + to_json(self) -> json:
}

class Ex1
{
    + Ex1(Building: str, Calls: str, Output: str) -> None
    - exporter(building: str, calls: str, output: str) -> dict, pd.DataFrame,pd.DataFrame
    - elevator_allocation(elev_list: list, call: int) -> int
    - time_calc(elev: Elevator, call: int) -> float
    - fill_output(output: pd.DataFrame, elev_num: int, call_num: int) -> None

}

class test
{
    + test_Elevator(self)
    + test_Ex1(self):
}

Elevator --> Ex1
Ex1 --> test

@enduml